CREATE TABLE `TABLA_VANS` (
	`ID` int AUTO_INCREMENT NOT NULL,
	`ACTIVA` boolean NOT NULL DEFAULT true,
	`VIN` varchar(17) NOT NULL,
	`MODELO` varchar(100) NOT NULL,
	`MATRICULA` varchar(20) NOT NULL,
	`NUM_POLIZA` varchar(50),
	`TIPO` varchar(50) NOT NULL,
	`EMPRESA` varchar(100) NOT NULL,
	`NUM_LLAVE` int,
	`ESTADO` varchar(50) NOT NULL,
	`ESTADO_ITV` boolean NOT NULL DEFAULT true,
	`FECHA_ITV` date,
	`AVERIA` boolean NOT NULL DEFAULT false,
	`FECHA_ACTIVACION` date,
	`FECHA_DEFLEETING` date,
	`FECHA_FIN_CONTRATO` date,
	`OBSERVACIONES` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TABLA_VANS_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TABLA_VANS_VIN_unique` UNIQUE(`VIN`),
	CONSTRAINT `TABLA_VANS_MATRICULA_unique` UNIQUE(`MATRICULA`)
);
--> statement-breakpoint
CREATE TABLE `VANS_AVERIAS` (
	`ID_AVERIA` int AUTO_INCREMENT NOT NULL,
	`ID` int NOT NULL,
	`CAUSA_AVERIA` text NOT NULL,
	`FECHA_AVERIA` date NOT NULL,
	`TALLER` varchar(100),
	`FECHA_ENTRADA_TALLER` date,
	`ESTIMACION_SALIDA` date,
	`FECHA_SALIDA_TALLER` date,
	`OBSERVACIONES_AVERIA` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `VANS_AVERIAS_ID_AVERIA` PRIMARY KEY(`ID_AVERIA`)
);
--> statement-breakpoint
ALTER TABLE `VANS_AVERIAS` ADD CONSTRAINT `VANS_AVERIAS_ID_TABLA_VANS_ID_fk` FOREIGN KEY (`ID`) REFERENCES `TABLA_VANS`(`ID`) ON DELETE cascade ON UPDATE no action;